import React, { useState, useEffect } from 'react';
import { api } from '../services/api';
import { AccessibilityReport } from '../types';
import { ScoreBadge } from '../components/ScoreBadge';
import {
  FileCheck2,
  Search,
  CheckCircle2,
  AlertTriangle,
  Sparkles,
  Calendar,
  User,
  ExternalLink,
  Building2
} from 'lucide-react';

interface AdminReportsPageProps {
  onNavigate: (path: string) => void;
}

export const AdminReportsPage: React.FC<AdminReportsPageProps> = ({ onNavigate }) => {
  const [reports, setReports] = useState<AccessibilityReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [selectedReport, setSelectedReport] = useState<AccessibilityReport | null>(null);

  useEffect(() => {
    const loadReports = async () => {
      setLoading(true);
      try {
        const res = await api.getReports();
        setReports(res.reports);
      } catch (err: any) {
        console.error('Failed to load reports:', err);
      } finally {
        setLoading(false);
      }
    };
    loadReports();
  }, []);

  const filteredReports = reports.filter(rep => {
    const matchesSearch =
      rep.locationName.toLowerCase().includes(search.toLowerCase()) ||
      rep.inspectorName.toLowerCase().includes(search.toLowerCase()) ||
      rep.id.toLowerCase().includes(search.toLowerCase());
    const matchesStatus = statusFilter === 'ALL' || rep.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <span className="text-xs font-bold uppercase tracking-wider text-purple-700 block">
            Audit Documentation Registry
          </span>
          <h1 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight">
            Accessibility Verification Reports
          </h1>
          <p className="text-sm text-slate-600 mt-1">
            Official inspection logs generated by certified accessibility auditors and computer vision models.
          </p>
        </div>

        <button
          onClick={() => onNavigate('/analyze')}
          className="inline-flex items-center gap-2 px-4 py-2 bg-purple-700 hover:bg-purple-800 text-white font-bold rounded-xl text-xs sm:text-sm transition shadow-2xs"
        >
          <Sparkles className="w-4 h-4" />
          Run New AI Audit
        </button>
      </div>

      {/* Filter and Search Bar */}
      <div className="bg-white rounded-2xl p-4 border border-slate-200 shadow-2xs flex flex-wrap items-center justify-between gap-3">
        <div className="flex-1 min-w-[220px] relative">
          <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search by facility, inspector, or report ID..."
            className="w-full pl-9 pr-4 py-2 rounded-xl border border-slate-300 text-xs sm:text-sm outline-hidden focus:ring-2 focus:ring-purple-600"
          />
        </div>

        <div className="flex items-center gap-2 text-xs">
          <span className="text-slate-500 font-medium">Status:</span>
          <select
            value={statusFilter}
            onChange={e => setStatusFilter(e.target.value)}
            className="px-2.5 py-1.5 rounded-lg border border-slate-300 font-semibold text-slate-800 bg-white"
          >
            <option value="ALL">All Statuses</option>
            <option value="VERIFIED">Verified (Compliant)</option>
            <option value="FLAGGED">Flagged (Action Needed)</option>
          </select>
        </div>
      </div>

      {/* Reports Table */}
      <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="bg-slate-50/80 border-b border-slate-200 text-slate-500 uppercase tracking-wider font-semibold">
                <th className="py-3.5 px-4">Report ID</th>
                <th className="py-3.5 px-4">Facility Name</th>
                <th className="py-3.5 px-4">Score & Rating</th>
                <th className="py-3.5 px-4">Inspector</th>
                <th className="py-3.5 px-4">Date</th>
                <th className="py-3.5 px-4">Status</th>
                <th className="py-3.5 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-slate-700">
              {filteredReports.map(rep => (
                <tr key={rep.id} className="hover:bg-slate-50/60">
                  <td className="py-3.5 px-4 font-mono font-bold text-slate-900">{rep.id}</td>
                  <td className="py-3.5 px-4 font-bold text-slate-900">{rep.locationName}</td>
                  <td className="py-3.5 px-4">
                    <ScoreBadge score={rep.score} category={rep.category} size="sm" />
                  </td>
                  <td className="py-3.5 px-4">{rep.inspectorName}</td>
                  <td className="py-3.5 px-4 font-mono text-slate-500">
                    {new Date(rep.createdAt).toLocaleDateString()}
                  </td>
                  <td className="py-3.5 px-4">
                    <span
                      className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-bold ${
                        rep.status === 'VERIFIED'
                          ? 'bg-emerald-100 text-emerald-800'
                          : 'bg-rose-100 text-rose-800'
                      }`}
                    >
                      {rep.status === 'VERIFIED' ? (
                        <CheckCircle2 className="w-3 h-3 text-emerald-600" />
                      ) : (
                        <AlertTriangle className="w-3 h-3 text-rose-600" />
                      )}
                      {rep.status}
                    </span>
                  </td>
                  <td className="py-3.5 px-4 text-right">
                    <button
                      onClick={() => setSelectedReport(rep)}
                      className="px-3 py-1 bg-slate-100 hover:bg-slate-200 text-slate-800 rounded-lg font-bold text-xs transition"
                    >
                      View Dossier
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {filteredReports.length === 0 && !loading && (
          <div className="p-12 text-center text-slate-500 text-xs">
            No inspection reports found matching criteria.
          </div>
        )}
      </div>

      {/* Selected Report Modal Details */}
      {selectedReport && (
        <div
          role="dialog"
          aria-modal="true"
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs"
        >
          <div className="bg-white rounded-3xl max-w-2xl w-full p-6 sm:p-8 shadow-2xl border border-slate-200 max-h-[90vh] overflow-y-auto space-y-6">
            <div className="flex items-start justify-between gap-4 pb-4 border-b border-slate-100">
              <div>
                <span className="text-xs font-mono font-bold text-slate-400 block">
                  {selectedReport.id}
                </span>
                <h3 className="text-xl font-bold text-slate-900">{selectedReport.locationName}</h3>
                <p className="text-xs text-slate-500">
                  Inspected by {selectedReport.inspectorName} on{' '}
                  {new Date(selectedReport.createdAt).toLocaleString()}
                </p>
              </div>
              <button
                onClick={() => setSelectedReport(null)}
                className="text-slate-400 hover:text-slate-700 font-bold text-lg p-1"
              >
                ✕
              </button>
            </div>

            <ScoreBadge
              score={selectedReport.score}
              category={selectedReport.category}
              showDetails={true}
              issues={selectedReport.issues}
              detectedFeatures={selectedReport.detections.map(d => d.class)}
            />

            {/* Recommendations */}
            <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 text-xs space-y-2">
              <span className="font-bold text-slate-800 block uppercase tracking-wider text-[11px]">
                Auditor Recommendations:
              </span>
              <ul className="list-disc list-inside text-slate-700 space-y-1">
                {selectedReport.recommendations.map((rec, i) => (
                  <li key={i}>{rec}</li>
                ))}
              </ul>
            </div>

            <div className="flex justify-end pt-2">
              <button
                onClick={() => setSelectedReport(null)}
                className="px-5 py-2 bg-slate-800 text-white rounded-xl text-xs font-bold"
              >
                Close Dossier
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
